version: '3.7'

services:
  php-fpm:
    build: docker
    container_name: 'php'
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    working_dir: /app
  nginx:
    image: nginx:1.21.1-alpine
    container_name: 'nginx'
    working_dir: /app
    ports:
      - 8000:80
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  db:
    image: postgres:13.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'root'
      POSTGRES_DB: 'test'
  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8090:8080